import { createHash } from "node:crypto";
import { tmpdir } from "node:os";
import { join } from "node:path";
import sharp from "sharp";
import { createWorker } from "tesseract.js";
import { assess, RULE_PACK } from "../src/rules.js";
import { validateDeclarations } from "../src/validation.js";

export async function gateway(body) {
  const response = await fetch(
    process.env.SUPABASE_URL + "/functions/v1/labelproof-worker",
    {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: "Bearer " + process.env.LABELPROOF_WORKER_SECRET,
      },
      body: JSON.stringify(body),
      signal: AbortSignal.timeout(30000),
    },
  );
  const data = await response.json();
  if (!response.ok) throw new Error(data.error || "Worker gateway unavailable");
  return data;
}
export async function readEvidence(input, index, scanId, worker) {
  // Signed URLs are generated by our machine-only gateway; never accept user URLs.
  const target = new URL(input.downloadUrl);
  if (
    target.origin !== new URL(process.env.SUPABASE_URL).origin ||
    !target.pathname.startsWith("/storage/v1/object/sign/labelproof-evidence/")
  )
    throw new Error("Untrusted evidence source");
  const response = await fetch(target, { signal: AbortSignal.timeout(20000) });
  if (!response.ok) throw new Error("Private photo download failed");
  const bytes = Buffer.from(await response.arrayBuffer());
  if (!bytes.length || bytes.length > 12582912)
    throw new Error("Photo exceeds 12 MiB");
  const hash = createHash("sha256").update(bytes).digest("hex");
  if (hash !== input.sha256)
    throw new Error("Photo hash does not match the uploaded evidence");
  const image = sharp(bytes, { limitInputPixels: 40000000, animated: false });
  const metadata = await image.metadata();
  if (
    !["png", "jpeg", "webp"].includes(metadata.format) ||
    !metadata.width ||
    !metadata.height ||
    (metadata.pages || 1) > 1
  )
    throw new Error("Upload a still JPG, PNG or WebP photo");
  const oriented = [5, 6, 7, 8].includes(metadata.orientation)
    ? { width: metadata.height, height: metadata.width }
    : { width: metadata.width, height: metadata.height };
  // Preserve original pixel coordinates; resize only the OCR input.
  const { data: prepared, info } = await image
    .autoOrient()
    .resize({
      width: 3000,
      height: 3000,
      fit: "inside",
      withoutEnlargement: true,
    })
    .greyscale()
    .normalize()
    .png()
    .toBuffer({ resolveWithObject: true });
  const { data } = await worker.recognize(
    prepared,
    {},
    { text: true, blocks: true },
  );
  const x = oriented.width / info.width,
    y = oriented.height / info.height;
  const lines =
    data.blocks?.flatMap((b) =>
      b.paragraphs.flatMap((p) =>
        p.lines.map((l) => ({
          text: l.text,
          confidence: l.confidence,
          bbox: {
            x0: l.bbox.x0 * x,
            y0: l.bbox.y0 * y,
            x1: l.bbox.x1 * x,
            y1: l.bbox.y1 * y,
          },
        })),
      ),
    ) || [];
  return {
    id: scanId + "-photo-" + index,
    scanId,
    storagePath: input.storagePath,
    sha256: hash,
    surface: input.surface,
    width: oriented.width,
    height: oriented.height,
    text: data.text.slice(0, 100000),
    lines,
    confidence: data.confidence,
    quality: data.confidence < 35 ? "Unreadable" : "Readable",
    qualityReason:
      "Server OCR confidence is an uncertainty signal. Human review is still required.",
    ocrEngine: "Tesseract.js 6 server",
    language: input.language,
    demo: false,
    createdAt: new Date().toISOString(),
  };
}
export function reportBundle(job, images) {
  const now = new Date().toISOString(),
    scanId = "cloud-job-" + job.id,
    assessmentId = scanId + "-v1";
  const product = {
    name: job.request.name,
    brand: "",
    category: "Other packaged food",
    origin: "Unknown",
    demo: false,
  };
  const findings = assess(images);
  return {
    scan: {
      ...product,
      id: scanId,
      processingJobId: job.id,
      createdAt: now,
      updatedAt: now,
      latestAssessmentId: assessmentId,
    },
    images,
    assessment: {
      id: assessmentId,
      scanId,
      version: 1,
      createdAt: now,
      reason: "Cloud OCR completed",
      rulePack: RULE_PACK,
      pipeline: "server-ocr-1.0",
      imageIds: images.map((i) => i.id),
      imageSnapshots: images.map(
        ({ id, sha256, surface, quality, width, height }) => ({
          id,
          sha256,
          surface,
          quality,
          width,
          height,
        }),
      ),
      productSnapshot: product,
      findings,
      declarationChecks: validateDeclarations(findings),
      reviewer: "Pending human review",
      demo: false,
    },
    event: {
      id: scanId + "-completed",
      scanId,
      type: "assessment",
      message: job.request.name + ": Cloud OCR completed (v1)",
      actor: "Cloud processing",
      at: now,
    },
  };
}
export async function processQueue(organization = null) {
  const { job } = await gateway({ action: "claim", organization });
  if (!job) return { claimed: false };
  let worker;
  try {
    worker = await createWorker(job.request.language, 1, {
      cachePath: join(tmpdir(), "labelproof-tessdata"),
      errorHandler: () => {},
    });
    const images = [];
    for (const [index, input] of job.request.images.entries()) {
      images.push(
        await readEvidence(
          { ...input, language: job.request.language },
          index,
          "cloud-job-" + job.id,
          worker,
        ),
      );
    }
    const result = await gateway({
      action: "finish",
      job: job.id,
      token: job.lease_token,
      bundle: reportBundle(job, images),
    });
    if (!result.accepted)
      throw new Error("Job lease changed before completion");
    console.info("labelproof_ocr_completed", {
      job: job.id,
      photos: images.length,
    });
    return { claimed: true, completed: true };
  } catch (error) {
    console.error("labelproof_ocr_failed", {
      job: job.id,
      message: error.message,
    });
    await gateway({
      action: "finish",
      job: job.id,
      token: job.lease_token,
      failure: String(error.message).slice(0, 1000),
    });
    return { claimed: true, completed: false };
  } finally {
    await worker?.terminate();
  }
}
