import { icon, esc, heading } from "../ui.js";
import { surfaces } from "../rules.js";
export function captureView(state, imageUrl) {
  const draft = state.draft;
  return `${heading(draft.scan.id ? "RESCAN & REASSESS" : "NEW PRODUCT SCAN", "Let’s see the whole picture.", "Capture clear packaging photos. We’ll turn the evidence into observations.")}
    <div class="capture-layout"><section class="panel"><div class="section-heading"><h2>Product details</h2><span class="badge not_captured">${icon("lock")} Saved on this device</span></div><div class="form-row"><label>Product name<input id="product-name" maxlength="120" value="${esc(draft.scan.name || "")}" placeholder="e.g. Wholegrain rolled oats"></label><label>Brand<input id="product-brand" maxlength="100" value="${esc(draft.scan.brand || "")}" placeholder="e.g. Earth & Grain"></label></div><div class="form-row"><label>Food category<select id="category">${["Cereals & grains", "Tea & beverages", "Snacks & mixes", "Other packaged food"].map((c) => `<option ${draft.scan.category === c ? "selected" : ""}>${c}</option>`).join("")}</select></label><label>Origin context<select id="origin">${["Unknown", "Domestic", "Imported"].map((c) => `<option ${draft.scan.origin === c ? "selected" : ""}>${c}</option>`).join("")}</select></label></div>
    <div class="capture-toolbar"><label>Surface for next photo<select id="surface">${surfaces.map((s) => `<option ${state.captureSurface === s ? "selected" : ""}>${s}</option>`).join("")}</select></label><label class="secondary camera-button" for="camera-file">${icon("camera")} Take a photo<input type="file" id="camera-file" accept="image/*" capture="environment"></label></div>
    <label class="dropzone" id="dropzone" for="file">${icon("scan-line")}<h3>Bring your label into focus</h3><p>Drop photos here or click to upload</p><span>JPG, PNG or WebP · 12 MB each · maximum 12 photos</span><input id="file" type="file" accept="image/jpeg,image/png,image/webp" multiple></label>
    <div class="upload-grid enhanced">${draft.images.map((image, i) => `<article class="upload-card"><img src="${imageUrl(image)}" alt="${esc(image.surface)} label"><div><label>Surface<select data-image-surface="${i}">${surfaces.map((s) => `<option ${image.surface === s ? "selected" : ""}>${s}</option>`).join("")}</select></label><label>Readability<select data-image-quality="${i}">${["Unknown", "Readable", "Unreadable"].map((q) => `<option ${image.quality === q ? "selected" : ""}>${q}</option>`).join("")}</select></label><small>${image.width} × ${image.height} ${image.sha256 ? "· Hashed" : ""}</small></div><button data-remove="${i}" aria-label="Remove ${esc(image.surface)} photo">${icon("x")}</button></article>`).join("")}</div>
    <div class="capture-actions"><a class="secondary" href="/dashboard">Cancel</a><button class="primary" data-action="analyze" ${!draft.images.length ? "disabled" : ""}>${icon("sparkles")} ${draft.scan.id ? "Reassess label" : "Review label"} ${icon("arrow-right")}</button></div><p class="fine-print">OCR runs in your browser. Quality signals are heuristic; human inspection is still needed. Detected text does not establish legal compliance.</p></section>
    <aside class="panel capture-guide"><span class="eyebrow">CAPTURE CHECKLIST</span><h2>Every side matters.</h2><p>Use an even light, a straight angle, and close-ups for small print. Suggested surfaces depend on packaging shape.</p>${surfaces.map((s) => `<div class="coverage-item">${icon(draft.images.some((i) => i.surface === s) ? "circle-check" : "circle")}<div><b>${s}</b><small>${draft.images.some((i) => i.surface === s) ? `${draft.images.filter((i) => i.surface === s).length} photo added` : "Not photographed"}</small></div></div>`).join("")}<div class="notice">${icon("lightbulb")}<span>A coverage checklist is a capture guide. It cannot prove that an unobserved declaration is absent.</span></div><a class="text-button" href="/dashboard/scans/demo-oats">Explore sample evidence ${icon("arrow-up-right")}</a></aside></div>`;
}
